version: "3.8"

x-django: &django
  build:
    context: .
    dockerfile: Dockerfile.prod
  env_file:
    - ./.env.prod
    - ./.env.db


services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - 5432
  redis:
    image: redis:alpine
  web:
    <<: *django
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_volume:/code/static
  celery:
    <<: *django
    command: celery -A dtb worker --loglevel=INFO
    depends_on:
      - redis
      - web
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/app/static
volumes:
  postgres_data:
  static_volume:
  media_volume: