version: "3.8"

x-django: &django
  build: .
  volumes:
    - .:/code
    - ./uuid:/uuid
  env_file:
    - ./.env
    - ./.env.db


services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - 5432
  redis:
    image: redis:alpine
  localtunnel:
    build: localtunnel
    command: bash -c "lt --subdomain `cat uuid/.env.uuid|cut -c6-` --local-host web --port 8000"
    volumes:
      - ./uuid:/uuid
  web:
    <<: *django
    command: python manage.py runserver_plus 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - localtunnel
      - db
  yarn:
    image: node
    command: bash -c "yarn --cwd /app install && yarn --cwd /app run dev"
    volumes:
      - ./react-modules:/app
    depends_on:
      - web
  #  bot:
  #    build: .
  #    container_name: dtb_bot
  #    command: python run_pooling.py
  #    env_file:
  #      - ./.env
  #    depends_on:
  #      - web
  celery:
    <<: *django
    command: celery -A dtb worker --loglevel=INFO
    depends_on:
      - redis
      - web
      - db
#  celery-beat:
#    build: .
#    container_name: dtb_beat
#    command: celery -A dtb beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
#    volumes:
#      - .:/code
#    env_file:
#      - ./.env
#    depends_on:
#      - redis
#      - celery
#      - web
#
volumes:
  postgres_data: