FROM node AS react

COPY react-modules /app
WORKDIR /app
RUN yarn install
RUN yarn run build

FROM python:3.10

ENV PYTHONUNBUFFERED=1

RUN mkdir /code
WORKDIR /code

COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /code
COPY --from=react /app/static /code/static

ENTRYPOINT ["/code/entrypoint.prod.sh"]
