FROM python:3.10 AS PROD

ENV PYTHONUNBUFFERED=1

RUN mkdir /code
WORKDIR /code

COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /code

FROM node AS react

COPY react-modules /app
WORKDIR /app
RUN yarn install
RUN yarn run build

FROM PROD AS PRODCOTNINUE
COPY --from=react /app /code/react-modules

ENTRYPOINT ["/code/entrypoint.prod.sh"]
