# Generated by Django 4.0.2 on 2022-02-11 20:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_alter_chatmember_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=''), default=list, size=4), default=list, size=None),
        ),
    ]
